@startuml

hide empty description

[*] --> Idle
Idle --> screenConfig : Display button
Idle --> startGame : Main buttons
startGame --> game : time, expectInput
screenConfig --> extradisplay : binary array (num)
startGame --> gamedisplay : roundCount
game --> roundSuccess : roundCount
game --> roundFail
roundSuccess --> gamedisplay : roundCount + 1
roundSuccess --> game : time, expectInput
roundFail --> gamedisplay : roundCount
roundFail --> Idle

Idle: Wait for main button(s) input,
Idle: Wait for display button input

screenConfig: int num;
screenConfig: Turn main buttons into binary input array
startGame: const startTime;
startGame: int time = startTime;
startGame: int roundCount;
startGame: int expectInput = rand(1-4);

game: Start timer (startTime),
game: Expect input (expectInput),
game: listen to input on other buttons

roundSuccess: roundCount = roundCount + 1;
roundSuccess: time = time / 2;
roundSuccess: expectInput = rand(1-4);
roundFail: delay(5000);
roundFail: roundCount = 0;

@enduml
